Pages/Committee/ApplicationDetails.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.IO.Compression;
using NuGet.Packaging;

namespace RatingManagementSystem.Pages.Committee
{
    [Authorize(Policy ="AccessApplication")]
    public class ApplicationDetailsModel : PageModel
    {
		private readonly IWebHostEnvironment _environment;

		public RatingSystemDbContext Context { get; set; }
		public UserManager<UserData> UserManager { get; set; }

		[BindProperty(SupportsGet = true)]
		public ApplicationData appdata { get; set; }

		[BindProperty(SupportsGet = true)]
		public IEnumerable<Thesis> jornal { get; set; }

		public List<(string propertyName, string filepath)> pdfFiles { get; set; } = new List<(string propertyName, string filepath)>();
		public ApplicationDetailsModel(RatingSystemDbContext db, UserManager<UserData> userManager, IWebHostEnvironment environment)
		{
			Context = db;
			UserManager = userManager;
			_environment = environment;
		}

		public async Task<IActionResult> OnGet(int id)
		{
			appdata = await Context.Applications.FirstOrDefaultAsync(a => a.ApplicationID == id);
			jornal = await Context.AppThesis.Where(a => a.ApplicationID == id).ToListAsync();
			var usr = await Context.Users.FirstOrDefaultAsync(b => b.Id == appdata.Id);


			var input = await UserManager.GetUserAsync(User);
			if (appdata == null) return Page();
			pdfFiles.Add(("PhDThesis", appdata.PhDThesisFilePath));
			pdfFiles.Add(("MasterThesis", appdata.MasterThesisFilePath));
			pdfFiles.Add(("CV", appdata.CVFilePath));
			// pdfFiles.Add(("Publications", appdata.PublicationsFilePath));
			pdfFiles.Add(("ConferenceParticipation", appdata.ConferenceParticipationFilePath));
			pdfFiles.Add(("PhDEquivalency", appdata.PhDEquivalencyFilePath));
			pdfFiles.Add(("RapportdeSoutenance", appdata.RapportdeSoutenanceFilePath));
			pdfFiles.Add(("BacCertificate", appdata.BacCertificateFilePath));
			pdfFiles.Add(("MasterCertificate", appdata.MasterCertificateFilePath));
			pdfFiles.Add(("PhDCertificate", appdata.PhDCertificateFilePath));
			//     pdfFiles.Add(("Other", appdata.OtherFilePath));

			int counter = 0, counter2 = 0;
			foreach (var file in appdata.PublicationsFilePath)
			{
				counter++;
				pdfFiles.Add(($"Publications-{counter}", file));
			}

			foreach (var file2 in appdata.OtherFilePath)
			{
				counter2++;
				pdfFiles.Add(($"Other-{counter2}", file2));
			}

			ViewData["Email"] = usr?.Email;
			ViewData["PhoneNumber"] = usr?.Phone;
			//


			return Page();
		}

		public async Task<IActionResult> OnPost(int id)
		{
			foreach (var jor in jornal)
			{
				var originalJor = await Context.AppThesis
			   .Include(a => a.Results) 
			   .FirstOrDefaultAsync(a => a.Id == jor.Id);

				if (originalJor != null)
				{
					if (originalJor.Results == null)
					{
						originalJor.Results = new FinalResult
						{
							TID = jor.Id,
							Desicion_ThesisOriginal = jor.Results.Desicion_ThesisOriginal,
							Desicion_ParticipationInConference = jor.Results.Desicion_ParticipationInConference,
							Desicion_Authentic = jor.Results.Desicion_Authentic,
							Desicion_Patented = jor.Results.Desicion_Patented,
							Desicion_PublishedInInternationalMagazine = jor.Results.Desicion_PublishedInInternationalMagazine,
							Desicion_PresentedInInternationalConference = jor.Results.Desicion_PresentedInInternationalConference
						};
						Context.Results.Add(originalJor.Results);
					}

					else
					{
						originalJor.Results.Desicion_ThesisOriginal = jor.Results.Desicion_ThesisOriginal;
						originalJor.Results.Desicion_ParticipationInConference = jor.Results.Desicion_ParticipationInConference;
						originalJor.Results.Desicion_Authentic = jor.Results.Desicion_Authentic;
						originalJor.Results.Desicion_Patented = jor.Results.Desicion_Patented;
						originalJor.Results.Desicion_PublishedInInternationalMagazine = jor.Results.Desicion_PublishedInInternationalMagazine;
						originalJor.Results.Desicion_PresentedInInternationalConference = jor.Results.Desicion_PresentedInInternationalConference;
						originalJor.Results.TID = jor.Id;

						Context.Results.Update(originalJor.Results); // Explicitly mark the Results entity as updated
					}

				}
			}
			var app = Context.Applications.Find(id);
			if (app == null) return Page();

			app.ApplicationStatus = "Results Are Available";
			Context.Applications.Update(app);

			await Context.SaveChangesAsync();
			return RedirectToPage("/Admin/Decision", new { Id = app.ApplicationID });
		}


		public async Task<IActionResult> OnPostDownload(int ApplicationID)
		{
			var uploadsPath = Path.Combine(_environment.WebRootPath, "Uploads");

			var appdataD = await Context.Applications.FindAsync(ApplicationID);
			string folderPath = appdataD.FolderPath;

			if (!string.IsNullOrEmpty(folderPath) && Directory.Exists(folderPath))
			{
				string folderName = Path.GetFileName(folderPath);
				string zipFileName = $"{folderName}_Converted.zip";
				string tempZipFilePath = Path.Combine(Path.GetTempPath(), zipFileName);

				try
				{
					ZipFile.CreateFromDirectory(folderPath, tempZipFilePath);

					var zipFileBytes = System.IO.File.ReadAllBytes(tempZipFilePath);

					return File(zipFileBytes, "application/zip", zipFileName);
				}
				finally
				{
					if (System.IO.File.Exists(tempZipFilePath))
					{
						System.IO.File.Delete(tempZipFilePath);
					}
				}
			}
			ModelState.AddModelError(string.Empty, "Invalid folder path.");
			return Page();

		}
	}
}

Pages/Committee/Apps/BioChemistryApps.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class BioChemistryAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public BioChemistryAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c=>c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

        ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "BioChemistry" && a.CreatedAt >date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }


      

    }
}

Pages/Committee/Apps/BiologyApps.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class BiologyAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public BiologyAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Biology" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }

    }
}

Pages/Committee/Apps/ChemistryApps.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class ChemistryAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public ChemistryAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Chemistry" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }
    }
}

Pages/Committee/Apps/ElectronicApps.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class ElectronicAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public ElectronicAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Electronic" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }
    }
}

Pages/Committee/Apps/GeologyApps.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class GeologyAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public GeologyAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Geology" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }
    }
}

Pages/Committee/Apps/InformaticsApps.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RatingManagementSystem.Data;
using RatingManagementSystem.Data.Models;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class InformaticsAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public InformaticsAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();
            
            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Informatics" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }
    }
}

Pages/Committee/Apps/MathApps.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RatingManagementSystem.Data.Models;
using RatingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace RatingManagementSystem.Pages.Committee.Apps
{
    [Authorize(Policy = "AccessApplication")]
    public class MathAppsModel : PageModel
    {
        private readonly UserManager<UserData> userManager;
        private readonly RatingSystemDbContext dbContext;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty(SupportsGet = true)]
        public List<ApplicationData> ApplicationData { get; set; }

        public MathAppsModel(UserManager<UserData> usr, RoleManager<IdentityRole> identrole, RatingSystemDbContext db)
        {
            userManager = usr;
            roleManager = identrole;
            dbContext = db;
        }
        public async Task<IActionResult> OnGet()
        {
            var usr = await userManager.GetUserAsync(User);
            var member = await dbContext.CommitteeMembers.FirstOrDefaultAsync(c => c.UserID == usr.Id);
            DateTime date = member.Joined;

            if (usr == null || member == null || date == null) return Page();

            ApplicationData = await dbContext.Applications.Where(a => a.DrMajor == "Math" && a.CreatedAt > date && a.ApplicationStatus == "Verified").ToListAsync();

            return Page();
        }
    }
}

Pages/Committee/ApplicationDetails.cshtml
@page
@model RatingManagementSystem.Pages.Committee.ApplicationDetailsModel
@{
}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/css/book-details.css">
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
	<div class="container">

		<h1 style="color:goldenrod">@Model.appdata.ThesisTitle </h1>
		<p style="color:saddlebrown">@Model.appdata.ApplicationStatus</p>
		<hr />

		<div class="row book-details">
			<div class="col-md-6 details">
				<dl class="row">
					<dt class="col-sm-4" style="color:saddlebrown">Doctor:</dt>
					<dd class="col-sm-8">@Model.appdata.FirstName @Model.appdata.LastName</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Major:</dt>
					<dd class="col-sm-8">@Model.appdata.DrMajor</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Doctor In Faculty of Science?:</dt>
					<dd class="col-sm-8">@Model.appdata.DrInFds</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Faculty:</dt>
					<dd class="col-sm-8">@Model.appdata.YourFaculty</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Defense Date & Location:</dt>
					<dd class="col-sm-8">
						@Model.appdata.DefenseDate &mdash; @Model.appdata.DefenseLocation &mdash; @Model.appdata.DefenseUniversity
					</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Email:</dt>
					<dd class="col-sm-8">@ViewData["Email"]</dd>
					<dt class="col-sm-4" style="color:saddlebrown">Phone Number:</dt>
					<dd class="col-sm-8">@ViewData["PhoneNumber"]</dd>
					

					<hr />
					@foreach (var pdfFile in Model.pdfFiles)
					{
						<dt class="col-sm-4" style="color:saddlebrown">@pdfFile.propertyName: </dt>
						<dd class="col-sm-8">
							<button class="btn btn-info" id="@($"OpenBtn-{pdfFile.propertyName}")">PreView Pdf</button>
							<div class="modal fade" id="@($"myModal-{pdfFile.propertyName}")" data-backdrop="static">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h2>@pdfFile.propertyName View</h2>
										</div>
										<div class="modal-body">
											<div class="ExternalFiles">
												<iframe src="/@Model.appdata.FolderPath/@pdfFile.filepath" width=100% height="600"></iframe>
											</div>
										</div>
									</div>
								</div>
							</div>
						</dd>
					}
				</dl>

				<hr />
					<h2> Thesis Journals</h2>
					@if (Model.jornal != null)
					{
						<ul class="thesis-journals ">
							<form method="post" id="myform">
								@{
									int i = 0;
								}
								@foreach (var jor in Model.jornal)
								{
									<dl class="row">
										<dd class="col-sm-4">
								<li>
									<h3>@jor.ResearchTitle</h3>
									<ul>
										<li>Journal Name: @jor.Journal</li>
										<li>Journal Number: @jor.JournalNumber</li>
										<li>Published Year: @jor.JournalYear</li>
										<li>
											Authors:
														@if (jor.Authors != null)
														{
															var auth = jor.Authors.Split(",");
												<ul>
																@foreach (var value in auth)
																{
														<li>@value</li>
																}
												</ul>
														}
										</li>
										<li>The Research Is:</li>
													@if (@jor.DecideIf != null)
													{
											<ul>
															@foreach (var value in @jor.DecideIf.Split(","))
															{
													<li>@value</li>
															}
											</ul>
													}
									</ul>
									<p>Additional Details: @jor.MembersContributionTResearch</p>
								</li>
								</dd>
							<dt class="col-sm-8">
								<h5> For Committee Only</h5>


								<div asp-validation-summary="All" style="color:goldenrod"></div>
								<div class="form-group">
									<label>Choose Your Application Type </label>

									<input type="hidden" asp-for="@jor.Id" name="@string.Concat($"jornal[{i}].Id")" />
									<input type="hidden" asp-for="@Model.appdata.ApplicationID" name="id" />

									<div class="form-check">
										<input class="form-check-input" type="radio" value="InsideThesis" asp-for="@jor.Results.Desicion_ThesisOriginal" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_ThesisOriginal).ToString())">
										<label class="form-check-label">InsideThesis</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="radio" value="OutsideThesis" asp-for="@jor.Results.Desicion_ThesisOriginal" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_ThesisOriginal).ToString())">
										<label class="form-check-label">OutsideThesis</label>
									</div>

									<div class="form-check">
										<input class="form-check-input" type="radio" value="FromThesisTopics" asp-for="@jor.Results.Desicion_ThesisOriginal" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_ThesisOriginal).ToString())">
										<label class="form-check-label">FromThesisTopics</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="true" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_ParticipationInConference).ToString())">
										<label class="form-check-label">ParticipationInConference</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="true" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_Authentic).ToString())">
										<label class="form-check-label">Is Authentic</label>
									</div>

									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="true" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_Patented).ToString())">
										<label class="form-check-label">Patented</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="true" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_PublishedInInternationalMagazine).ToString())">
										<label class="form-check-label">PubInternationalMagazine</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="true" name="@string.Concat($"jornal[{i}].",Html.NameFor(model => model.jornal.FirstOrDefault().Results.Desicion_PresentedInInternationalConference).ToString())">
										<label class="form-check-label">PresInInternationalConf</label>
									</div>
								</div>



							</dt>
						</dl>

									i++;
								}
					<button class="update-btn btn btn-outline-secondary" onclick="submitForm()" asp-for="@Model.jornal"> Update Result</button>
					</form>
					</ul>

					}
					else
					{
					<p>No thesis journals found for this application.</p>
					}
				




		

				@* <form method="post" asp-page-handler="Download" >
					<input type="hidden" asp-for="@Model.appdata.ApplicationID"/>
					<button type="submit">Download</button>
				</form> *@

				<a asp-page="Decision" class="btn btn-outline-warning" asp-route-id="@Model.appdata.ApplicationID">Decision</a>
				<a asp-page="AllThesisRateApplications" class="btn btn-secondary">Back to List</a>


			</div>
		</div>
	</div>



	@section Scripts {
		<script>

			@foreach (var item in Model.pdfFiles)
			{
				<text>
					$("#OpenBtn-@item.propertyName").click(function () {
						$("#myModal-@item.propertyName").modal('show');
					});
				</text>
			}
		</script>
	}
</body>
</html>




<script>
	function submitForm() {
		document.getElementById("myform").submit();
	}
</script>

Pages/Committee/BioChemistry.cshtml
@page
@model RatingManagementSystem.Pages.Committee.BioChemistryModel
@{
}

<hr />
<h4 style="color:#DAE438"> Choose Committee Members - BioChemistry Section</h4>
<hr />
@if (Model.UserInfoComit.Any())
{
    <form method="post">
        <div class="Container">
            <div class="row book-details">
                <div class="col-md-8 details">
                    @foreach (var dr in Model.UserInfoComit)
                    {
                        var isMember = Model.Members.Any(a => a.UserID == dr.Id);

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label" style="color:#A39C11">@dr.FirstName @dr.LastName</label>
                            <div class="col-sm-8">
                                <input type="checkbox" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].isInCommittee" value="true" @(isMember ? "checked" : "") />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].FirstName" value="@dr.FirstName" />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].LastName" value="@dr.LastName" />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].Id" value="@dr.Id" />
                            </div>
                        </div>
                    }

                    <input type="submit" class="btn btn-outline-warning" value="Save" />
                </div>
            </div>
        </div>
    </form>

}

Pages/Committee/Biology.cshtml
@page
@model RatingManagementSystem.Pages.Committee.BiologyModel
@{
}
<hr />

<h4 style="color:darkorchid"> Choose Committee Members - Biology Doctors</h4>
<hr />
@if (Model.UserInfoComit.Any())
{
    <form method="post">
        <div class="Container">
            <div class="row book-details">
                <div class="col-md-8 details">
                    @foreach (var dr in Model.UserInfoComit)
                    {
                        var isMember = Model.Members.Any(a => a.UserID == dr.Id);

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label" style="color:#6111A3">@dr.FirstName @dr.LastName</label>
                            <div class="col-sm-8">
                                <input type="checkbox" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].isInCommittee" value="true" @(isMember ? "checked" : "") />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].FirstName" value="@dr.FirstName" />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].LastName" value="@dr.LastName" />
                                <input type="hidden" name="UserInfoComit[@Model.UserInfoComit.IndexOf(dr)].Id" value="@dr.Id" />
                            </div>
                        </div>
                    }

                    <input type="submit" class="btn btn-outline-warning" value="Save" />
                </div>
            </div>
        </div>
    </form>

}